# Generated by Django 3.1.3 on 2020-12-19 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask_yakovitskiy', '0009_auto_20201118_0107'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likeanswer',
            unique_together={('user', 'answer')},
        ),
        migrations.AlterUniqueTogether(
            name='likequestion',
            unique_together={('user', 'question')},
        ),
    ]
