# Generated by Django 3.1.3 on 2020-11-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_yakovitskiy', '0005_auto_20201117_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likequestion',
            name='opinion',
            field=models.BooleanField(default=True, null=True, verbose_name='Мнение'),
        ),
    ]
