# Generated by Django 3.1.3 on 2020-11-17 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask_yakovitskiy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likeanswer',
            options={'verbose_name': 'Лайк на ответ', 'verbose_name_plural': 'Лайки на ответы'},
        ),
        migrations.AlterModelOptions(
            name='likequestion',
            options={'verbose_name': 'Лайк на вопрос', 'verbose_name_plural': 'Лайки на вопросы'},
        ),
    ]
