# Generated by Django 3.1.3 on 2020-11-17 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_yakovitskiy', '0003_auto_20201117_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Рейтинг'),
        ),
    ]
