# Generated by Django 3.1.3 on 2020-11-18 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_yakovitskiy', '0008_auto_20201118_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeanswer',
            name='opinion',
            field=models.BooleanField(default=True, null=True, verbose_name='Мнение'),
        ),
    ]
