# Generated by Django 3.1.3 on 2020-11-18 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_yakovitskiy', '0006_auto_20201117_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeanswer',
            name='opinion',
            field=models.IntegerField(null=True, verbose_name='Мнение'),
        ),
    ]
