# Generated by Django 3.1.3 on 2020-11-18 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask_yakovitskiy', '0007_auto_20201118_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeanswer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask_yakovitskiy.answer', verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='likeanswer',
            name='opinion',
            field=models.IntegerField(default=1, null=True, verbose_name='Мнение'),
        ),
    ]
