# Generated by Django 3.1.3 on 2020-12-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_yakovitskiy', '0009_auto_20201118_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='question-mark.jpg', max_length=1024, null=True, upload_to='avatar/%y/%m/%d', verbose_name='Аватар'),
        ),
    ]
